#! /bin/bash

# Do this from one level up so "imgcomp" is part of the path.
cd ..

# Compress it with lzma (better than gzip and bzip2, faster than bzip2)
# Want to have high compression ratio because I'm icluding all this libjpeg stuff.
tar --lzma --exclude=".git" -cvf imgcomp/imgcomp.tar.lzma imgcomp/README.txt imgcomp/make* \
 imgcomp/free_up_space imgcomp/setup-imgcomp* imgcomp/make_zip_release \
 imgcomp/docs/*.html imgcomp/libjpeg/*.h imgcomp/libjpeg/*.c imgcomp/libjpeg/makefile

echo
echo "Created file imgcomp.tar.lzma"
echo "This file can be unpacked with the following command:"
echo "   tar --lzma -xvf imgcomp.tar.lzma"






