#! /bin/bash
# This script setups up imgcomp to run at startup
# It is assumed that setup-imgcomp has already been run.
# This script assumes imgcomp is in /home/pi/imgcomp

# Make sure the camera is enabled

if [ ! -f ../imgcomp ]; then
	echo "You need to build imgcomp first."
    echo "Go into the imgcomp directorytype \"make\" to build it."
	exit 1
fi

if [[ $EUID -ne 0 ]]; then
	echo "Parts of this script require administrator priviledged."
	echo "You may be propted to enter your password"
fi

if grep -q "start_x\=1" /boot/config.txt; then
	echo "    camera module is already enabled"
else	
	echo "camera is not enabled."
    echo "Run raspi-config to it under 'Interfacing Options'"
	exit 1
fi

# Make sure a configuration file exists
if [ -e ../../imgcomp.conf ] ; then
	echo "    imcomp.conf file aready in /home/pi"
else
	echo "copy imcomp.conf.example to /home/pi/imgcomp.conf"
	cp -a ../conf-examples/imgcomp.conf.example ~/imgcomp.conf
fi

if [ -d /ramdisk ]; then
	echo "    ramdisk mount point already exists"
else
	echo "making /ramdisk mount point"
	sudo mkdir /ramdisk
fi

if grep -q "/ramdisk" /etc/fstab; then
	echo "    fstab already contains entry for ramdisk"
else
	echo "Adding ramdisk entry to fstab"
	echo "tmpfs   /ramdisk        tmpfs   nodev,nosuid,size=20M   0       0" | sudo tee -a  /etc/fstab > /dev/null
	sudo mount /ramdisk
fi


