#! /bin/bash
# This script setups up imgcomp to run at startup
# It is assumed that setup-imgcomp has already been run.
# This script assumes imgcomp is in /home/pi/imgcomp

if crontab -l 2>/dev/null | grep -q "imgcomp/imgcomp"; then
	echo "    crontab entry for starting at startup already exists"
else
	echo "Adding crontab entry to start imcgomp at startup"
	crontab -l 2>/dev/null| { cat; echo "@reboot imgcomp/imgcomp &"; \
		echo "0 * * * * imgcomp/setup/relaunch_imgcomp"; } | crontab -
fi
